package dev.mulcor.core.region;

import dev.mulcor.registry.ItemId;
import dev.mulcor.registry.Items;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Crafting ({@code CraftingMenu}, {@code InventoryMenu}, {@code ResultSlot}): the result of the player's 2×2 grid or
 * a crafting table's 3×3 grid, and what taking it consumes. Recipes come from {@code recipes.txt} (generated by
 * {@code tools/gen_recipes.py}); an ingredient is a set of items (a tag or a single item), matched per cell like
 * vanilla's {@code Ingredient}.
 *
 * <p>Matching follows {@code CraftingInput}: the grid is trimmed to the bounding box of its non-empty cells; a shaped
 * recipe matches when its pattern has exactly that size and matches cell by cell, as is or mirrored left to right; a
 * shapeless recipe matches when every non-empty cell takes a distinct ingredient. Special recipes (fireworks, map
 * cloning, armour dyeing, tool repair, banners) are not ported.
 */
final class Crafting {
    private static final int WORDS = (ItemId.COUNT + 63) >>> 6;
    private static final int SHAPED = 0, SHAPELESS = 1;

    // recipe r: kind, width, height (shapeless: ingredient count), result stack, first cell in CELLS
    private static final int[] KIND, WIDTH, HEIGHT, FIRST;
    private static final long[] RESULT;
    /** Ingredient set index per cell (-1: empty), in recipe order. */
    private static final int[] CELLS;
    /** Item bit sets, {@link #WORDS} longs each. */
    private static final long[] SETS;
    /** Recipes by grid size: shaped {@code w + h * 4} (1..3 × 1..3), shapeless {@code 16 + ingredient count}. */
    private static final int[][] BY_SIZE = new int[26][];
    /** {@code Item.getCraftingRemainder}: the item left in the grid (bucket, glass bottle), or 0. */
    private static final int[] REMAINDER = new int[ItemId.COUNT];

    static {
        List<int[]> recipes = new ArrayList<>();
        List<Long> results = new ArrayList<>();
        List<Integer> cells = new ArrayList<>();
        Map<String, Integer> setIndex = new HashMap<>();
        List<long[]> sets = new ArrayList<>();
        try (var in = Crafting.class.getResourceAsStream("/dev/mulcor/core/recipes.txt")) {
            if (in == null) throw new IllegalStateException("recipes.txt missing");
            var reader = new BufferedReader(new InputStreamReader(in, StandardCharsets.UTF_8));
            for (String line; (line = reader.readLine()) != null; ) {
                if (line.isEmpty() || line.charAt(0) == '#') continue;
                String[] f = line.split(" ");
                boolean shaped = f[0].equals("S");
                int p = 1;
                int w = shaped ? Integer.parseInt(f[p++]) : 0, h = shaped ? Integer.parseInt(f[p++]) : 0;
                int result = Items.byName("minecraft:" + f[p++]);
                int count = Integer.parseInt(f[p++]);
                int n = f.length - p;
                if (result <= 0 || (!shaped && n > 9)) continue;
                int first = cells.size();
                boolean ok = true;
                for (int i = p; i < f.length; i++) {
                    if (f[i].equals("-")) {
                        cells.add(-1);
                        continue;
                    }
                    Integer s = setIndex.get(f[i]);
                    if (s == null) {
                        long[] bits = new long[WORDS];
                        boolean any = false;
                        for (String name : f[i].split("\\|")) {
                            int item = Items.byName("minecraft:" + name);
                            if (item > 0) {
                                bits[item >>> 6] |= 1L << item;
                                any = true;
                            }
                        }
                        s = any ? sets.size() : -2;
                        if (any) sets.add(bits);
                        setIndex.put(f[i], s);
                    }
                    if (s == -2) ok = false;
                    cells.add(s);
                }
                if (!ok) { // an ingredient with no item of this version: drop the recipe
                    while (cells.size() > first) cells.removeLast();
                    continue;
                }
                recipes.add(new int[] {shaped ? SHAPED : SHAPELESS, shaped ? w : n, shaped ? h : n, first});
                results.add(Stacks.of(result, count));
            }
        } catch (IOException e) {
            throw new IllegalStateException(e);
        }
        int n = recipes.size();
        KIND = new int[n];
        WIDTH = new int[n];
        HEIGHT = new int[n];
        FIRST = new int[n];
        RESULT = new long[n];
        int[] perSize = new int[BY_SIZE.length];
        for (int r = 0; r < n; r++) {
            int[] d = recipes.get(r);
            KIND[r] = d[0];
            WIDTH[r] = d[1];
            HEIGHT[r] = d[2];
            FIRST[r] = d[3];
            RESULT[r] = results.get(r);
            perSize[sizeKey(r)]++;
        }
        for (int k = 0; k < BY_SIZE.length; k++) BY_SIZE[k] = new int[perSize[k]];
        java.util.Arrays.fill(perSize, 0);
        for (int r = 0; r < n; r++) BY_SIZE[sizeKey(r)][perSize[sizeKey(r)]++] = r;
        CELLS = cells.stream().mapToInt(Integer::intValue).toArray();
        SETS = new long[sets.size() * WORDS];
        for (int i = 0; i < sets.size(); i++) System.arraycopy(sets.get(i), 0, SETS, i * WORDS, WORDS);
        int bucket = Items.byName("minecraft:bucket"), bottle = Items.byName("minecraft:glass_bottle");
        for (String b : new String[] {"milk_bucket", "water_bucket", "lava_bucket", "powder_snow_bucket"}) {
            int i = Items.byName("minecraft:" + b);
            if (i > 0) REMAINDER[i] = bucket;
        }
        for (String b : new String[] {"honey_bottle", "dragon_breath"}) {
            int i = Items.byName("minecraft:" + b);
            if (i > 0) REMAINDER[i] = bottle;
        }
    }

    private Crafting() {}

    private static int sizeKey(int r) {
        return KIND[r] == SHAPED ? WIDTH[r] + HEIGHT[r] * 4 : 16 + WIDTH[r];
    }

    /** The number of recipes loaded (for tests). */
    static int recipeCount() {
        return RESULT.length;
    }

    private static boolean inSet(int set, int item) {
        return (SETS[set * WORDS + (item >>> 6)] >>> item & 1) != 0;
    }

    /** First menu slot of the grid and its width for a menu kind. */
    private static int gridStart(int kind) {
        return kind == Menus.CRAFTING ? PlayerInv.TABLE_GRID : PlayerInv.CRAFT;
    }

    private static int gridWidth(int kind) {
        return kind == Menus.CRAFTING ? 3 : 2;
    }

    private static int resultSlot(int kind) {
        return kind == Menus.CRAFTING ? PlayerInv.TABLE_RESULT : PlayerInv.RESULT;
    }

    /**
     * {@code CraftingMenu.slotChangedCraftingGrid}: set the result slot to the matching recipe's result (empty if
     * none). Called after every change to the grid.
     */
    static void slotsChanged(Region r, int eid, int kind) {
        long result = Stacks.EMPTY;
        int recipe = find(r, eid, kind);
        if (recipe >= 0) result = RESULT[recipe];
        int slot = resultSlot(kind);
        if (PlayerInv.get(r, eid, slot) != result) PlayerInv.set(r, eid, slot, result);
    }

    /**
     * The recipe matching player {@code eid}'s grid, or -1. Uses the region's scratch: {@code craft[0..3]} = the
     * trimmed box (left, top, width, height).
     */
    static int find(Region r, int eid, int kind) {
        int start = gridStart(kind), gw = gridWidth(kind);
        int minX = gw, minY = gw, maxX = -1, maxY = -1, filled = 0;
        for (int y = 0; y < gw; y++) {
            for (int x = 0; x < gw; x++) {
                if (PlayerInv.get(r, eid, start + x + y * gw) == Stacks.EMPTY) continue;
                filled++;
                minX = Math.min(minX, x);
                maxX = Math.max(maxX, x);
                minY = Math.min(minY, y);
                maxY = Math.max(maxY, y);
            }
        }
        if (filled == 0) return -1;
        int w = maxX - minX + 1, h = maxY - minY + 1;
        int[] shaped = BY_SIZE[w + h * 4];
        for (int i = 0; i < shaped.length; i++) {
            int rec = shaped[i];
            if (matchesShaped(r, eid, start, gw, minX, minY, rec, false) || matchesShaped(r, eid, start, gw, minX, minY, rec, true)) {
                return rec;
            }
        }
        if (filled > 9) return -1;
        int[] shapeless = BY_SIZE[16 + filled];
        int[] items = r.craftItems;
        int k = 0;
        for (int y = minY; y <= maxY; y++) {
            for (int x = minX; x <= maxX; x++) {
                long s = PlayerInv.get(r, eid, start + x + y * gw);
                if (s != Stacks.EMPTY) items[k++] = Stacks.item(s);
            }
        }
        for (int i = 0; i < shapeless.length; i++) {
            int rec = shapeless[i];
            if (assign(items, filled, FIRST[rec], 0, 0)) return rec;
        }
        return -1;
    }

    private static boolean matchesShaped(Region r, int eid, int start, int gw, int left, int top, int rec, boolean mirror) {
        int w = WIDTH[rec], h = HEIGHT[rec], first = FIRST[rec];
        for (int y = 0; y < h; y++) {
            for (int x = 0; x < w; x++) {
                int set = CELLS[first + (mirror ? w - 1 - x : x) + y * w];
                long s = PlayerInv.get(r, eid, start + left + x + (top + y) * gw);
                if (set < 0) {
                    if (s != Stacks.EMPTY) return false;
                } else if (s == Stacks.EMPTY || !inSet(set, Stacks.item(s))) {
                    return false;
                }
            }
        }
        return true;
    }

    /** Shapeless: give ingredient {@code i} and on a distinct item (bitmask {@code used}); true if all fit. */
    private static boolean assign(int[] items, int n, int first, int i, int used) {
        if (i == n) return true;
        int set = CELLS[first + i];
        for (int k = 0; k < n; k++) {
            if ((used >>> k & 1) == 0 && inSet(set, items[k]) && assign(items, n, first, i + 1, used | 1 << k)) return true;
        }
        return false;
    }

    /**
     * {@code ResultSlot.onTake}: take one item from every non-empty grid cell and leave its crafting remainder
     * (merged into the cell, else into the inventory, else dropped); then the result is recomputed.
     */
    static void onTake(Region r, int eid, int kind) {
        int start = gridStart(kind), gw = gridWidth(kind);
        for (int i = 0; i < gw * gw; i++) {
            int slot = start + i;
            long s = PlayerInv.get(r, eid, slot);
            if (s == Stacks.EMPTY) continue;
            int rem = REMAINDER[Stacks.item(s)];
            s = Stacks.withCount(s, Stacks.count(s) - 1);
            PlayerInv.set(r, eid, slot, s);
            if (rem == 0) continue;
            long remainder = Stacks.of(rem, 1);
            if (s == Stacks.EMPTY) {
                PlayerInv.set(r, eid, slot, remainder);
            } else if (Stacks.sameItemSameComponents(s, remainder)) {
                PlayerInv.set(r, eid, slot, Stacks.withCount(s, Stacks.count(s) + 1));
            } else {
                long left = PlayerInv.add(r, eid, remainder);
                if (left != Stacks.EMPTY) ItemEntities.dropFromPlayer(r, eid, left, false);
            }
        }
        slotsChanged(r, eid, kind);
    }
}
