#!/usr/bin/env python3
"""Generate mulcor-core's crafting recipe table from minecraft-data (pc/26.1 recipes.json + items.json).

minecraft-data expands tag ingredients into one recipe per tag member (every cell of one key gets the same item);
recipes with the same result, count and shape are merged back into per-cell ingredient sets, which is how vanilla
matches tag ingredients (each cell independently).

Output (mulcor-core/src/main/resources/dev/mulcor/core/recipes.txt), one recipe per line:
  S <width> <height> <result> <count> <cell>...   shaped, row-major; a cell is '-' or item names joined by '|'
  L <result> <count> <ingredient>...              shapeless
Usage: gen_recipes.py <minecraft-data/data/pc/26.1> <out>
"""
import json, sys, os

src, out = sys.argv[1], sys.argv[2]
recipes = json.load(open(os.path.join(src, 'recipes.json')))
items = {i['id']: i['name'] for i in json.load(open(os.path.join(src, 'items.json')))}

shaped, shapeless = {}, {}
order = []
for rid, lst in recipes.items():
    for r in lst:
        res = items[r['result']['id']]
        cnt = r['result']['count']
        if 'inShape' in r:
            shape = r['inShape']
            h, w = len(shape), max(len(row) for row in shape)
            cells = [(row[i] if i < len(row) else None) for row in shape for i in range(w)]
            key = ('S', res, cnt, w, h, tuple(c is None for c in cells))
            if key not in shaped:
                shaped[key] = [[] for _ in cells]
                order.append(key)
            for i, c in enumerate(cells):
                if c is not None and items[c] not in shaped[key][i]:
                    shaped[key][i].append(items[c])
        else:
            ing = r['ingredients']
            key = ('L', res, cnt, len(ing))
            if key not in shapeless:
                shapeless[key] = [[] for _ in ing]
                order.append(key)
            for i, c in enumerate(ing):
                if items[c] not in shapeless[key][i]:
                    shapeless[key][i].append(items[c])

# minecraft-data keeps one member of the "dye any other colour" ingredient (colorItemWithDye): restore the rest.
COLORS = ['white', 'orange', 'magenta', 'light_blue', 'yellow', 'lime', 'pink', 'gray', 'light_gray', 'cyan',
          'purple', 'blue', 'brown', 'green', 'red', 'black']
for key, cells in shapeless.items():
    res = key[1]
    if len(cells) != 2 or not cells[0][0].endswith('_dye'):
        continue
    color = cells[0][0][:-4]
    suffix = res[len(color) + 1:] if res.startswith(color + '_') else None
    if suffix in ('bed', 'carpet', 'wool', 'harness'):
        cells[1] = [c + '_' + suffix for c in COLORS if c != color]

with open(out, 'w') as f:
    f.write('# generated by tools/gen_recipes.py from minecraft-data pc/26.1; do not edit\n')
    for key in order:
        if key[0] == 'S':
            _, res, cnt, w, h, _ = key
            cells = ['-' if not s else '|'.join(s) for s in shaped[key]]
            f.write(f'S {w} {h} {res} {cnt} ' + ' '.join(cells) + '\n')
        else:
            _, res, cnt, _ = key
            f.write(f'L {res} {cnt} ' + ' '.join('|'.join(s) for s in shapeless[key]) + '\n')
print(len(order), 'recipes')
