#!/usr/bin/env python3
"""Generate mulcor-core's harvest table from minecraft-data (pc/26.1 blocks.json + items.json).

For every block that requires the correct tool for drops (BlockBehaviour.requiresCorrectToolForDrops), the items
that are correct for it (Tool.isCorrectForDrops). Output (mulcor-core/src/main/resources/dev/mulcor/core/harvest.txt):
  <block> <item>|<item>...
Usage: gen_blocktools.py <minecraft-data/data/pc/26.1> <out>
"""
import json, sys, os

src, out = sys.argv[1], sys.argv[2]
blocks = json.load(open(os.path.join(src, 'blocks.json')))
items = {i['id']: i['name'] for i in json.load(open(os.path.join(src, 'items.json')))}
n = 0
with open(out, 'w') as f:
    f.write('# generated by tools/gen_blocktools.py from minecraft-data pc/26.1; do not edit\n')
    for b in blocks:
        tools = b.get('harvestTools')
        if tools:
            f.write(b['name'] + ' ' + '|'.join(items[int(k)] for k in tools) + '\n')
            n += 1
print(n, 'blocks')
